---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}
@import url('https://fonts.googleapis.com/css2?family=Cal+Sans&family=Roboto&display=swap');

h2 {
  font-family: "Cal Sans";
}

* {
  font-family: "Roboto";
}

#how-long-are-armand-and-austins-commutes-to-and-from-university {
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(15px);
  position: relative;
  width: 90vw;
  padding: 20px;
  border-radius: 20px;
  margin: 40px auto;
}

body {
  background-image: url("https://austin-540.github.io/stats220/docs/blob-scene-haikei3.svg");
  background-size: cover;
  background-color: black;
  background-repeat: no-repeat;
} 

img {
  border: 5px solid black;
  margin: 10px;
}

```

## How long are Armand and Austin's commutes to and from university?

```{r}
library(tidyverse)

logged_data <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRetKKj9bMRzvsbYOusSWE0uw2oEJIxmDjFP6C2U79SCUlN05jlOH4OHHo5kVT4mpo5BdYi9q9NZh7w/pub?gid=49993136&single=true&output=csv")

latest_data <- rename(logged_data, timestamp = 1, method = 2, duration = 3, start_time = 4)



latest_data_durations.rounded <- latest_data$duration %>% 
  round(-1) #Round the durations to the 10s place
latest_data.rounded <- latest_data
latest_data.rounded$duration <- latest_data_durations.rounded #then insert the rounded durations into a data frame

ggplot(latest_data.rounded) + 
  geom_bar(aes(x=duration, fill = method)) + 
  theme_minimal() +
  labs(x = "Duration in minutes - rounded to the closest 10 minutes",
       y = "Number of journies",
       title = "Durations of tracked commutes to and from campus.",
  )


latest_data.bus <- latest_data
latest_data.car <- latest_data
for (i in nrow(latest_data):1) { #I'm sure we will cover a much better way of doing this in a future module...
  if (latest_data$method[i] == "Bus") {
    latest_data.car <- latest_data.car[-i,]
  } else if (latest_data$method[i] == "Car") {
    latest_data.bus <- latest_data.bus[-i,]
  } 
}#Starting with the final element, go through each element and remove it from the different dfs if it isn't the corresponding method

mean_times <- data.frame(method=c("Bus", "Car"), duration=c(mean(latest_data.bus$duration), mean(latest_data.car$duration)))
ggplot(mean_times) + 
  geom_col(aes(x=method, y=duration), fill="#16cd25") + #Had to switch the type of geom here
  theme_minimal() +
  labs(x = "Transportation method", y = "Mean duration in minutes",
       title = "Mean commute duration by method")

```

There have been **`r nrow(latest_data)`** commutes timed in the data. The mean commute length recorded is **`r round(mean(latest_data$duration),0)`** minutes.

***


Coco's (dynamic) reaction to this information:

```{r}
library(magick)

happy_coco <- image_read("https://austin-540.github.io/stats220/docs/coco-happy.jpg") %>% 
  image_resize("400x400") %>% #I am aware that one of those values isn't doing anything
  image_annotate(text = "How I feel speeding past the cars \nin the bus lane", size=20, gravity = "north", boxcolor = "#FFFFFF")

surprised_coco <- image_read("https://austin-540.github.io/stats220/docs/coco-surprised.jpg") %>%
  image_resize("400x400") %>%
  image_annotate(text = "My face when the bus \nthat stops at every bus stop is \nslower than a car that doesn't", size=20, gravity = "north", boxcolor = "#FFFFFF")

if (mean(latest_data.bus$duration) > mean(latest_data.car$duration)) { #If the mean bus journey is longer
  surprised_coco #Then show the surprised image
} else {
  happy_coco
} #If the means are exactly equal then it shows the happy Coco image 
#which I think is an acceptable thing to happen
#because I like seeing happy Coco pictures
```