---
title: "Project 4"
author: "Austin Sarney"
output: 
  html_document:
    code_folding: hide
  
---


```{css echo=FALSE}
@import url('https://fonts.googleapis.com/css2?family=Cal+Sans&family=Micro+5&display=swap');

.author, .title, .subtitle, h2 {
    margin: 0px 0px 10px 0px;
}

.title {
    color: #FFF !important;
}

.author {
    background: linear-gradient(90deg,rgba(255, 0, 0, 1) 0%, rgba(255, 149, 0, 1) 20%, rgba(255, 229, 0, 1) 40%, rgba(0, 255, 149, 1) 60%, rgba(0, 47, 255, 1) 80%, rgba(191, 0, 255, 1) 100%);
    /* I had to put a gradient somewhere :) */
    background-clip: text;
    color: rgba(0,0,0,0);
    background-size: 100% 100%;
    background-repeat: no-repeat;
    display: block;
    width: max-content;
    margin: 0px 0px 10px 0px;
    font-family: "Micro 5", sans-serif;display: block;
    font-size: 40px; /* I do not know why Micro 5 looks so small by default */
    text-shadow: 2px -2px 0 rgba(255, 255, 255, 0.7);/* to make it readable */
}

body {background: #ECEBE4;} 

h1, h2, h3 {font-family: "Cal Sans", sans-serif;display: block; color: #49306B;}

div#header {
  background: #49306B !important;
  border-radius: 10px; 
  padding: 20px;
  margin: 20px;
}

div.section {
  background: rgba(255, 255, 255, 0.8);
  border-radius: 10px; 
  padding: 20px;
  margin: 20px;
  
  animation: slideIn ease-in-out both;
  animation-timeline: view();
  animation-range: entry 10% entry 30%;
  
}

html {
overflow-x: hidden;
}

.figcaption {
  color: #777;
}

@keyframes slideIn {
from {transform: translateX(50vw); background: rgba(73, 48, 107, 0.5)}
to {transform: translateX(0px); background: rgba(255, 255, 255, 0.8)}
}

@media (prefers-reduced-motion: reduce) {div.section, div#header {animation: none !important;}}
/* I hope the animation isn't too obnoxious for everyone else... */



```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This is a section

## Visual data story

This is a section

## Learning reflection

This is a section

## Appendix
```{r file='data_visualisation.R', eval=FALSE, echo=TRUE}

```
